version: "3"

services:
  ros2:
    # image: osrf/ros:humble-desktop-full-jammy # gazeboも使用するならfull
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ../:/workspaces/${COMPOSE_PROJECT_NAME:?error empty COMPOSE_PROJECT_NAME}:cached
    tty: true
    command: sleep infinity
    working_dir: /workspaces/${COMPOSE_PROJECT_NAME:?error empty COMPOSE_PROJECT_NAME}
